In [1]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT *
        FROM FACILITIES
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(2, 'Badminton Court', 0, 15.5, 4000, 50)
(3, 'Table Tennis', 0, 5, 320, 10)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)
(7, 'Snooker Table', 0, 5, 450, 15)
(8, 'Pool Table', 0, 5, 400, 15)

### *Q10: Produce a list of facilities with a total revenue less than 1000. The output of facility name and total revenue, sorted by revenue. Remember that there's a different cost for guests and members!*

In [2]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT f.name,
        SUM(CASE WHEN b.memid = 0 THEN b.slots * f.guestcost
            ELSE b.slots * f.membercost END) AS cost
        FROM Facilities AS f
        INNER JOIN Bookings AS b
        USING (facid)
        GROUP BY f.name
        HAVING cost < 1000
        ORDER BY cost
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Table Tennis', 180)
('Snooker Table', 240)
('Pool Table', 270)

### *Q11: Produce a report of members and who recommended them in alphabetic surname,firstname order*

SELECT m2.memid AS MemID,  
       m2.recommendedby AS RecommenderID,  
       CONCAT(m2.firstname, ' ', m2.surname)  AS Membername,  
       CONCAT(m1.firstname, ' ', m1.surname)  AS Reccommendername  

FROM Members as m1  
INNER JOIN Members as m2  
ON m1.memid = m2.recommendedby  
WHERE m1.memid != 0  
ORDER BY Membername

In [3]:
import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
       SELECT m2.memid AS MemID,
       m2.recommendedby AS RecommenderID,
       m2.firstname || ' ' || m2.surname AS Membername,
       m1.firstname || ' ' || m1.surname AS Reccommendername       
       FROM Members as m1
       INNER JOIN Members as m2
       ON m1.memid = m2.recommendedby
       WHERE m1.memid != 0
       ORDER BY m1.surname, m1.firstname
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(24, '15', 'Ramnaresh Sarwin', 'Florence Bader')
(22, '16', 'Joan Coplin', 'Timothy Baker')
(20, '5', 'Matthew Genting', 'Gerald Butters')
(16, '13', 'Timothy Baker', 'Jemima Farrell')
(17, '13', 'David Pinker', 'Jemima Farrell')
(27, '20', 'Henrietta Rumney', 'Matthew Genting')
(26, '11', 'Douglas Jones', 'David Jones')
(7, '4', 'Nancy Dare', 'Janice Joplette')
(11, '4', 'David Jones', 'Janice Joplette')
(35, '30', 'John Hunt', 'Millicent Purview')
(8, '3', 'Tim Boothe', 'Tim Rownam')
(4, '1', 'Janice Joplette', 'Darren Smith')
(5, '1', 'Gerald Butters', 'Darren Smith')
(10, '1', 'Charles Owen', 'Darren Smith')
(14, '1', 'Jack Smith', 'Darren Smith')
(21, '1', 'Anna Mackenzie', 'Darren Smith')
(29, '2', 'Henry Worthington-Smyth', 'Tracy Smith')
(30, '2', 'Millicent Purview', 'Tracy Smith')
(36, '2', 'Erica Crumpet', 'Tracy Smith')
(12, '9', 'Anne Baker', 'Ponder Stibbons')
(15, '9', 'Florence Bader', 'Ponder Stibbons')
(9, '6', 'Ponder Stibbons', 'Burton Tracy')

### *Q12: Find the facilities with their usage by member, but not guests*

In [4]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT m.firstname || ' ' || m.surname AS Membername, COUNT(b.facid) AS count
        FROM Bookings as b
        LEFT JOIN Facilities AS F
        USING (facid)
        LEFT JOIN Members AS m
        USING (memid)
        WHERE m.firstname || ' ' || m.surname NOT LIKE '%GUEST'
        GROUP BY b.memid
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Darren Smith', 261)
('Tracy Smith', 210)
('Tim Rownam', 408)
('Janice Joplette', 159)
('Gerald Butters', 163)
('Burton Tracy', 176)
('Nancy Dare', 117)
('Tim Boothe', 188)
('Ponder Stibbons', 104)
('Charles Owen', 131)
('David Jones', 115)
('Anne Baker', 118)
('Jemima Farrell', 80)
('Jack Smith', 89)
('Florence Bader', 120)
('Timothy Baker', 166)
('David Pinker', 71)
('Matthew Genting', 72)
('Anna Mackenzie', 126)
('Joan Coplin', 53)
('Ramnaresh Sarwin', 70)
('Douglas Jones', 14)
('Henrietta Rumney', 20)
('David Farrell', 34)
('Henry Worthington-Smyth', 41)
('Millicent Purview', 16)
('Hyacinth Tupperware', 16)
('John Hunt', 15)
('Erica Crumpet', 7)

*Q13: Find the facilities usage by month, but not guests*

In [5]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT strftime('%m', b.starttime) AS Month, COUNT(b.facid) AS count
        FROM Bookings as b
        LEFT JOIN Facilities AS F
        USING (facid)
        LEFT JOIN Members AS m
        USING (memid)  
        WHERE memid != 0
        GROUP BY MONTH
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('07', 480)
('08', 1168)
('09', 1512)